### ISSUE TITLE
Failure in ghci on Windows

### ISSUE THREAD

**Issue by ndmitchell** [haskell-foundation/foundation#326] opened 2017-06-11 06:04 UTC
I modified weeder to use foundation strings. I loaded it in ghci, but running gives:

```
ghc.exe: C:\Users\Neil\AppData\Roaming\cabal\x86_64-windows-ghc-8.0.2\foundation-0.0.10-2WPaw9Yl85PEz44LOCUDJh\HSfoundation-0.0.10-2WPaw9Yl85PEz44LOCUDJh.o: unknown symbol `clock_gettime'
```

I can reproduce with `runhaskell Test.hs` where `Test.hs` is defined as:

```
import Foundation as F
main = F.putStrLn (F.fromString "Hello")
```

I suggest adding that to the test suite.

**Comment by ndmitchell** [comment] 2017-06-11 07:33
See https://stackoverflow.com/questions/5404277/porting-clock-gettime-to-windows for how to avoid calling clock_time.

**Comment by RyanGlScott** [comment] 2017-06-11 16:07
FWIW, this is an occurrence of a known GHC bug, [Trac #13120](https://ghc.haskell.org/trac/ghc/ticket/13210), which has been fixed in GHC 8.2.1. A workaround is to link against `pthread` explicitly:

```
$ runghc Bug.hs
ghc.exe: C:\Users\RyanGlScott\AppData\Roaming\cabal\x86_64-windows-ghc-8.0.2\foundation-0.0.10-2WPaw9Yl85PEz44LOCUDJh\HSfoundation-0.0.10-2WPaw9Yl85PEz44LOCUDJh.o: unknown symbol `clock_gettime'

Bug.hs: Bug.hs: unable to load package `foundation-0.0.10'

$ runghc -lpthread Bug.hs
Hello
```

**Comment by NicolasDP** [comment] 2017-06-11 18:16
@RyanGlScott , thanks for the heads up. Didn't it was a GHC bug.

**Comment by vincenthz** [comment] 2017-06-12 18:24
I wonder if it's a cabal only problem. I've extensively tested on windows 7 & 10 before pushing this to master (albeit all with stack)

**Comment by vincenthz** [comment] 2017-06-15 10:36
ok I managed to reproduce using runghc, sadly I have no idea how to properly switch to a compat definition when needed; it works with `clock_gettime` for an unknown reason when compiling a program with stack, which I expect something about mingw that get linked on or some include, no idea ..

**Closed** 2017-06-15 14:10 UTC
Labels: bug, bug:windows

**Comment by RyanGlScott** [comment] 2017-06-15 14:18
Right, it's specifically an issue with the runtime linker, which is typically only invoked from GHCi or `runghc` (and not from compiled code, i.e., `cabal build`/`stack build`).

You can make this work with both compiled code and GHCi by simply adding this to `foundation.cabal`:

```
if os(windows):
  extra-libraries: pthread
```

**Comment by ndmitchell** [comment] 2017-06-16 20:03
Has a test case been added to appveyor that just does runhaskell over a trivial foundation program? Exactly this bug has cropped up twice, and broken Stackage once, so testing for it seems a very good idea.

**Comment by RyanGlScott** [comment] 2017-06-16 20:05
Using `F.putStrLn (F.fromString "Hello")` in a Template Haskell computation should also invoke the runtime linker (and tickle this bug).

**Comment by vincenthz** [comment] 2017-06-17 08:47
I didn't manage to write such a test that does this in a one liner (or two liners); also the only way that I've got to reproduce is to run with hackage latest version's which is less than ideal to make sure the current state of the repo works.

**Comment by ndmitchell** [comment] 2017-06-17 09:20
I'll work on a test.

**Comment by RyanGlScott** [comment] 2017-06-17 14:57
Here's a simple (compiled) test:

```haskell
{-# LANGUAGE TemplateHaskell #-}
module Main (main) where

import Foundation as F
import Language.Haskell.TH

main :: IO ()
main = $(do runIO $ F.putStrLn (F.fromString "Hello")
            [| return () |])
```

With `foundation-0.0.10`:

```
$ ghc Bug.hs -package foundation-0.0.10
[1 of 1] Compiling Main             ( Bug.hs, Bug.o )
ghc.exe: unable to load package `foundation-0.0.10'
ghc.exe: C:\Users\RyanGlScott\AppData\Roaming\cabal\x86_64-windows-ghc-8.0.2\foundation-0.0.10-2WPaw9Yl85PEz44LOCUDJh\HSfoundation-0.0.10-2WPaw9Yl85PEz44LOCUDJh.o: unknown symbol `clock_gettime'
```

With `foundation-0.0.11`:

```
$ ghc Bug.hs -package foundation-0.0.11
[1 of 1] Compiling Main             ( Bug.hs, Bug.o )
ghc.exe: unable to load package `foundation-0.0.11'
ghc.exe: C:\Users\RyanGlScott\AppData\Roaming\cabal\x86_64-windows-ghc-8.0.2\foundation-0.0.11-IOlwuxWCg3MKPQ9GBrU1js\HSfoundation-0.0.11-IOlwuxWCg3MKPQ9GBrU1js.o: unknown symbol `foundation_time_clock_gettime'
```

**Comment by RyanGlScott** [comment] 2017-06-17 15:43
The former error can be fixed with the advice in https://github.com/haskell-foundation/foundation/issues/326#issuecomment-308747377.

The latter bug happens because a code path in `foundation_time.c` depends on the `FOUNDATION_SYSTEM_API_NO_CLOCK` macro, which is `#define`d in [Haskell](https://github.com/haskell-foundation/foundation/blob/4b7c23352e6af4cac332eaf2e615d2c625ccaf04/Foundation/System/Bindings/Time.hsc#L52-L54), not C, so the `foundation_time.c` file doesn't think `FOUNDATION_SYSTEM_API_NO_CLOCK` is defined!

**Comment by RyanGlScott** [comment] 2017-06-17 16:21
I've opened #360 to fix this issue.
